import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from "./_components/header";

const inter = Inter({
  subsets: ["latin"],
  display: "auto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} antialiased`}
      >
        <Header />
        {children}
        
        
      </body>
    </html>
  );
}
